version: '3'

services:
  lab-config:
    image: lab-config:1.0.0-snapshot
    restart: always
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://lab-eureka:8080/eureka"
    volumes:
      - "./configuration:/var/lab-config/configuration"

  lab-eureka:
    image: lab-eureka:1.0.0-snapshot
    restart: always
    ports:
      - "8090:8080"

  lab-participant-1:
    image: lab-participant:1.0.0-snapshot
    restart: always
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://lab-config:8080"
      EUREKA_INSTANCE_INSTANCE_ID: "1"
      
  lab-participant-2:
    image: lab-participant:1.0.0-snapshot
    restart: always
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://lab-config:8080"
      EUREKA_INSTANCE_INSTANCE_ID: "2"

  lab-participant-db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_DB: "lab_participant_db"
      POSTGRES_USER: "lab_participant_user"
      POSTGRES_PASSWORD: "lab_participant_password"
    volumes:
      - lab-participant-db-data:/var/lib/postgresql/data
  
  lab-tournament:
    image: lab-tournament:1.0.0-snapshot
    restart: always
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://lab-config:8080"
      
  lab-tournament-db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_DB: "lab_tournament_db"
      POSTGRES_USER: "lab_tournament_user"
      POSTGRES_PASSWORD: "lab_tournament_password"
    volumes:
      - lab-tournament-db-data:/var/lib/postgresql/data    

  lab-gateway:
    image: lab-gateway:1.0.0-snapshot
    restart: always
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://lab-config:8080"
      LAB_GATEWAY_HOST: "lab-gateway:8080"

  lab-angular:
    image: lab-angular:1.0.0-snapshot
    restart: always
    environment:
      API_URL: http://lab-gateway:8080/api
    ports:
      - "8086:80"
      
volumes:
    lab-participant-db-data:
    lab-tournament-db-data:
